### ISSUE TITLE
will the training coding release?

### ISSUE THREAD

**Issue by bixueting** [facebookresearch/DiT#15]
Very useful work. Very looking forward to training scripts！

**Comment by youngwanLEE** [comment]
It would be better to let us know if the authors release the code or not.

**Comment by wpeebles** [comment]
Hi @bixueting  and @youngwanLEE, we just released a training script in the latest commit. You can find more info in the README.

**Comment by Yoonho-Na** [comment]
@wpeebles Thank you!

**Comment by youngwanLEE** [comment]
@wpeebles many thanks!!!
