### ISSUE TITLE
Can u give the procedure of the calculate FiD Score

### ISSUE THREAD

**Issue by heepengpeng** [facebookresearch/DiT#16]

**Comment by wpeebles** [comment]
Hi @heepengpeng, you can find a script [here](https://github.com/facebookresearch/DiT/issues/8) that's been implemented to mass-sample 50K images to compute various stats including FID. Once you run that script, you can use ADM's TensorFlow evaluation suite: https://github.com/openai/guided-diffusion/tree/main/evaluations

**Comment by heepengpeng** [comment]
> 

How to get the sample .npz by DiT. Use DiT to generate 50K images and store it in npz?

**Comment by wpeebles** [comment]
I believe the script in this thread (https://github.com/facebookresearch/DiT/issues/8) generates the npz file automatically.

**Comment by heepengpeng** [comment]
> I believe the script in this thread (#8) generates the npz file automatically.

Do u use DiT generate 1000 classes images，and each class has 50。Then use script to generate npz file

**Comment by wpeebles** [comment]
Actually we just randomly-sample the class labels in every mini-batch uniformly over the 1000 classes, so in expectation you'd expect to get ~50 per class, but we don't enforce it.

**Comment by heepengpeng** [comment]
> 

thanks a lot
