### ISSUE TITLE
About unconditional training script

### ISSUE THREAD

**Issue by Suimingzhe** [facebookresearch/DiT#18]
Thanks for your code.

I would like to know how do I modify the training script ”torchrun --nnodes=1 --nproc_per_node=N train.py --model DiT-XL/2 --data-path /path/to/FFHQ“ when I train an unconditional DiT, for example on the FFHQ dataset.

Best Regards.

**Comment by wpeebles** [comment]
Hi @Suimingzhe. There's a few ways you could go about this. Possibly the easiest way would be to call `train.py` with `--num-classes 1` and structure your dataset so that [ImageFolder](https://pytorch.org/vision/main/generated/torchvision.datasets.ImageFolder.html) thinks there's only one class. You might also want to consider passing `class_dropout_prob=0` when calling the DiT constructor. We didn't experiment much with unconditional models, so this is all somewhat experimental, but hopefully it's a good starting point.

**Comment by Suimingzhe** [comment]
Thank you very much for such a quick reply! I will try your suggestion and thanks again.

**Comment by Suimingzhe** [comment]
@wpeebles I notice you used the pre-trained autoencoder. If I want to train an uncondition DiT on FFHQ dataset, is it right that I need to train a new autoencoder first according to latent diffusion? Thanks.

**Comment by wpeebles** [comment]
The VAE is unconditional, so you don't necessarily need to train a new one (although you could). We just reused the LDM/Stable Diffusion VAE models in our paper. It's a good idea to check that the pre-trained VAE gives good reconstructions on FFHQ before using it though.

**Comment by hdjsjyl** [comment]
hi @Suimingzhe ， is it possible to get some feedback about training unconditional DiT? Are you successful? If yes, which way you use? Thanks

**Comment by Suimingzhe** [comment]
Just as author suggested, you can：
1. set "num-classes=1", which means all your images belong to one class, so the shape of "embedding_table" is [1, hidden_size];
2. set "class_dropout_prob=0.0", which means you do not use classifier-free guidance for training, and you also should use "model.forward" rather than "model.forward_with_cfg" for sampling;

**Comment by Suimingzhe** [comment]
> hi @Suimingzhe ， is it possible to get some feedback about training unconditional DiT? Are you successful? If yes, which way you use? Thanks

Just as author suggested, you can：

1. set "num-classes=1", which means all your images belong to one class, so the shape of "embedding_table" is [1, hidden_size];
2. set "class_dropout_prob=0.0", which means you do not use classifier-free guidance for training, and you also should use "model.forward" rather than "model.forward_with_cfg" for sampling;
