### ISSUE TITLE
The FID score improvement brought by cfg

### ISSUE THREAD

**Issue by raywzy** [facebookresearch/DiT#19]
Thanks for the awesome work and clean code! I have a small question regarding the FID score. While using the cfg with a small number like 1.25 on only the first 3 channels, we could see that the FID metric is improved significantly!

What are the potential reasons? Thanks!

**Comment by wpeebles** [comment]
Classifier-free guidance rocks! :) I don't think we have a great understanding of why it works so well, but other models (like the LDM U-Net) also exhibit significant improvement with a relatively small amount of guidance. DiT certainly benefits a lot from it, although I'm not sure if it benefits disproportionately more or less than other DDPMs.
