### ISSUE TITLE
Some generated pictures looks like wrong, have u ever meet this ?

### ISSUE THREAD

**Issue by heepengpeng** [facebookresearch/DiT#20]
![sampleLcBDmJrC](https://user-images.githubusercontent.com/122354463/218948314-867d4c52-b1dc-4bb7-8f0e-2b9e6668cee7.png)

**Comment by wpeebles** [comment]
Hi @heepengpeng. I haven't seen samples like this before :) is this sampling from the pre-trained DiT models? would you mind sharing a code snippet/ more details?

**Comment by heepengpeng** [comment]
> Hi @heepengpeng. I haven't seen samples like this before :) is this sampling from the pre-trained DiT models? would you mind sharing a code snippet/ more details?

https://github.com/heepengpeng/minddiffusion/tree/main/vision/DiT  code is here. I use the the pre-trained DiT models. I rewrite the code by another  AI framework   MindSpore

**Comment by heepengpeng** [comment]
And Some pictures looks like  good, some looks like wrong

**Comment by heepengpeng** [comment]
https://github.com/heepengpeng/minddiffusion/blob/main/vision/DiT/mainV2.py

**Comment by wpeebles** [comment]
So it's a bit hard to tell if there's an issue from one sample, but if there is it's likely with the mindspore codebase. If you can reproduce the issue with the PyTorch codebase, let me know and I'll try to take a look.
