### ISSUE TITLE
How to speed up sampling process?

### ISSUE THREAD

**Issue by yxchng** [facebookresearch/DiT#25]
The sampling process is extremely slow. Do you have any advice on how to speed it up?

**Comment by heepengpeng** [comment]
try use GPU，and more batchsize

**Comment by wpeebles** [comment]
If you're using a recent GPU that supports `tf32` (most notable A100s), you can add the following to the top of `sample.py` (or `train.py`) to substantially increase speed:

```python
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
```

There are a lot of other possibilities to speed things up (like using Flash Attention or `torch.compile` in PyTorch 2.0).

**Comment by wpeebles** [comment]
I added these by default in the latest commit. For our 512x512 DiT-XL/2 model, it decreases the time to sample 8 images with 250 sampling steps + guidance on 1x A100 GPU from ~320 seconds to <100 seconds (>3x speedup).
