### ISSUE TITLE
What's the meaning of 0.18215 

### ISSUE THREAD

**Issue by NIL-zhuang** [facebookresearch/DiT#32]
Hello, thank you for sharing your code.
I've seen the magic number 0.18215 in your code, both training and sampling. It seems you scale the encoder output, I am wondering what does that mean.

**Comment by NathanYanJing** [comment]
I used to have the same question, but this is from the stable diffusion tradition.  You can find more here: https://github.com/huggingface/diffusers/issues/437, hope this helps!

**Comment by wpeebles** [comment]
Hi @NIL-zhuang and @NathanYanJing, you can find more info about it here: https://github.com/facebookresearch/DiT/issues/13#issuecomment-1407947246
