### ISSUE TITLE
About 512x512 training details.

### ISSUE THREAD

**Issue by whlzy** [facebookresearch/DiT#33]
Hi! 
Nice work! 🎉
Have you ever experimented with PyTorch training on Imagenet with 512x512 resolution on A100 (80G)? 
And what batch size do you use?
I would greatly appreciate it if you could provide more training details on 512x512 resolution. 
Thank you! 😊

**Comment by wpeebles** [comment]
Hi @whlzy, I haven't tried training at 512x512 resolution in PyTorch, but it should work out-of-the-box assuming it fits on GPU. To reproduce the paper's 512x512 XL/2 experiment, I believe the only change you'd need to make to the default `train.py` command is adding `--image-size 512`. Across all experiments in our paper, the only training hyperparameters we varied were model config (patch size, transformer size) and image resolution (256 vs 512). All other hyperparameters were constant across experiments (lr=constant 1e-4, global batch size=256, etc.). If training doesn't fit in GPU memory, you may need to look into optimized attention implementations (flash attention, xformers, etc.).

**Comment by whlzy** [comment]
Thank you very much for your answer!
