### ISSUE TITLE
Can a pretrained DiT directly be used in classification task?

### ISSUE THREAD

**Issue by Colezwhy** [facebookresearch/DiT#58]
Since the architecture of DiT has only minimal changes compared to ViTs, and I wonder if a pretrained DiT(maybe conditional trained or finetuned on some classification datasets) can be used in classification or other dense prediction tasks? And what about their performances?

**Comment by namhhn** [comment]
Hi @Colezwhy, did you find out how to apply DIT for classification tasks?

**Comment by juneleung** [comment]
+1
