### ISSUE TITLE
possible bug for sampling script: y_null = torch.tensor([1000] * n)

### ISSUE THREAD

**Issue by forever208** [facebookresearch/DiT#77]
hi @wpeebles, thanks for open-sourcing the awesome code.
 
this `y_null` setting looks wrong for non-imagenet datasets
should it be changed from `1000` to `num_classes`?

**Comment by ZenoNing** [comment]
Yes, definitely. Otherwise, when you change your dataset to another, which has a different number of classes, the program will report an error.
